name: ecopocket_clean_architecture
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  go_router: ^9.0.3
  google_fonts: ^5.1.0
  intl: ^0.18.0
  path: ^1.8.3
  # riverpod: ^2.3.6
  sqflite: ^2.2.8+4
  freezed_annotation:
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  shared_preferences: ^2.2.0
  collection: ^1.17.1
  step_progress_indicator: ^1.0.2
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.5
  build_runner: ^2.4.5
  riverpod_generator:

flutter:
  generate: true
  uses-material-design: true

  assets:
    - google_fonts/
    - assets/illustrations/
    - assets/icons/

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  watch: flutter pub run build_runner watch
